#!/usr/bin/env python3
"""caelestia postHook: generate a kitty colour theme from the current scheme.

Fires on every scheme change (wallpaper switch, dark/light toggle) via the
caelestia CLI's theme/wallpaper postHook. Writes kitty colour directives to
~/.config/kitty/caelestia.conf, which kitty.conf includes in place of the
stale JaKooLit wallust theme.

Colour mapping mirrors caelestia's apply_terms() escape sequences:
  foreground = onSurface, background = surface, cursor/selection = secondary,
  color0-15 = term0-15.
"""

import json
import os
from pathlib import Path

colours = json.loads(os.environ["SCHEME_COLOURS"])


def hx(key: str) -> str:
    return "#" + colours[key].lstrip("#")


lines = [
    "# Generated by caelestia postHook — do not edit",
    f"foreground {hx('onSurface')}",
    f"background {hx('surface')}",
    f"cursor {hx('secondary')}",
    f"selection_background {hx('secondary')}",
]
lines += [f"color{i} {hx(f'term{i}')}" for i in range(16)]

out = Path.home() / ".config/kitty/caelestia.conf"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines) + "\n")
# Also dump the raw palette for other consumers (e.g. caelestia-fetch.py
# terminal header) so they can follow the theme without re-querying.
cache = Path.home() / ".cache/caelestia/palette.json"
cache.parent.mkdir(parents=True, exist_ok=True)
cache.write_text(json.dumps(colours))
